/// <reference path="../../lib/phaser.comments.d.ts"/>

/**
 * Class which picks the correct instrument information given
 * a reduced name.
 * 
 * @class InstrumentFactory
 */
class InstrumentFactory {

    /**
     * Get the autogenerated information string for a named
     * instrument and tuning.
     * 
     * @static
     * @param {string} name 
     * @returns {string} 
     * @memberof InstrumentFactory
     */
    public static getInstrumentData(name:string):string {
        // Remove brackets and make L/C
        name = name.replace("(","").replace(")","").toLowerCase();
        return instrument_diatonicc4.information;
    }
}